### ISSUE TITLE
Jurassic Dashboard

### ISSUE THREAD

**Issue by hannahhreed** [hannahhreed/jurassic-dashboard#1]
Submitting manually, markbot says we are missing files that we aren't. Said you would manually put in the mark.

Thank you!
Hannah Reed 02

**Comment by hannahhreed** [comment]
@charlie-quinn 
Forgot to tag you above!

**Comment by charlie-quinn** [comment]
- [ ] move `favicon-196.png` out of your images folder and into your root assignment folder (this is where favicons should always live)
- [ ] you'll still need to create your `favicon.ico` file using http://www.xiconeditor.com/

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
@hannahhreed ⚠️`Reminder: please close this issue since it has been resolved or expired.`

**Comment by charlie-quinn** [comment]
@hannahhreed ⚠️`Reminder: please close this issue since it has been resolved or expired.`

**Comment by charlie-quinn** [comment]
@hannahhreed ⚠️`Reminder: please close this issue since it has been resolved or expired.`
